"""add fifa pmsr report extraction

Revision ID: 88b0b3c50e5c
Revises: aba802112a71
Create Date: 2026-06-21 02:27:55.738419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88b0b3c50e5c'
down_revision: Union[str, Sequence[str], None] = 'aba802112a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_report_metric_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_key', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('scope', sa.String(length=24), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('aggregation', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('definition_version', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_key')
    )
    op.create_table('squad_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('position', sa.String(length=4), nullable=False),
    sa.Column('squad_number', sa.Integer(), nullable=False),
    sa.Column('fc26_overall', sa.Integer(), nullable=False),
    sa.Column('market_value_meur', sa.Float(), nullable=False),
    sa.Column('season_rating_2024_25', sa.Float(), nullable=True),
    sa.Column('season_rating_2023_24', sa.Float(), nullable=True),
    sa.Column('season_rating_2022_23', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'squad_number')
    )
    op.create_index('ix_squad_players_team', 'squad_players', ['team_id'], unique=False)
    op.create_table('player_injuries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=False),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('days_out', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['squad_players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_player_injuries_player', 'player_injuries', ['player_id'], unique=False)
    op.create_table('match_report_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('raw_pdf_uri', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('official_match_number', sa.Integer(), nullable=True),
    sa.Column('template_key', sa.String(length=80), nullable=True),
    sa.Column('template_version', sa.String(length=40), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('pdf_metadata_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_index('ix_match_report_documents_match', 'match_report_documents', ['match_id'], unique=False)
    op.create_index('ix_match_report_documents_status', 'match_report_documents', ['status'], unique=False)
    op.create_table('match_report_extraction_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_version', sa.String(length=40), nullable=False),
    sa.Column('template_version', sa.String(length=40), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('coverage', sa.Float(), nullable=True),
    sa.Column('artifact_root', sa.Text(), nullable=False),
    sa.Column('stats_json', sa.JSON(), nullable=False),
    sa.Column('error_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('coverage IS NULL OR (coverage >= 0 AND coverage <= 1)'),
    sa.CheckConstraint('quality_score IS NULL OR (quality_score >= 0 AND quality_score <= 1)'),
    sa.ForeignKeyConstraint(['document_id'], ['match_report_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'pipeline_version', 'template_version', 'attempt')
    )
    op.create_index(op.f('ix_match_report_extraction_runs_status'), 'match_report_extraction_runs', ['status'], unique=False)
    op.create_index('ix_match_report_runs_document_created', 'match_report_extraction_runs', ['document_id', 'created_at'], unique=False)
    op.create_index('ux_match_report_runs_active', 'match_report_extraction_runs', ['document_id'], unique=True, sqlite_where=sa.text('is_active = 1'))
    op.create_table('match_report_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('page_type', sa.String(length=64), nullable=False),
    sa.Column('section', sa.String(length=64), nullable=True),
    sa.Column('team_scope', sa.String(length=80), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('width_points', sa.Float(), nullable=False),
    sa.Column('height_points', sa.Float(), nullable=False),
    sa.Column('rotation', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('render_uri', sa.Text(), nullable=False),
    sa.Column('render_sha256', sa.String(length=64), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=False),
    sa.Column('raw_element_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['match_report_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['match_report_extraction_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'page_number')
    )
    op.create_index('ix_match_report_pages_run_type', 'match_report_pages', ['run_id', 'page_type'], unique=False)
    op.create_table('match_report_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('artifact_type', sa.String(length=32), nullable=True),
    sa.Column('source_bbox_json', sa.JSON(), nullable=True),
    sa.Column('source_element_ids_json', sa.JSON(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['match_report_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['match_report_extraction_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_match_report_issues_run_severity', 'match_report_issues', ['run_id', 'severity'], unique=False)
    op.create_index('ix_match_report_issues_unresolved', 'match_report_issues', ['run_id', 'is_resolved'], unique=False)
    op.create_table('match_report_page_payloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('payload_type', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('element_count', sa.Integer(), nullable=False),
    sa.Column('mapped_count', sa.Integer(), nullable=False),
    sa.Column('decorative_count', sa.Integer(), nullable=False),
    sa.Column('unresolved_count', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['match_report_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'payload_type')
    )
    op.create_index('ix_match_report_payloads_page', 'match_report_page_payloads', ['page_id'], unique=False)
    op.create_table('match_report_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('squad_player_id', sa.Integer(), nullable=True),
    sa.Column('team_source_name', sa.String(length=100), nullable=False),
    sa.Column('source_name', sa.String(length=160), nullable=False),
    sa.Column('normalized_name', sa.String(length=160), nullable=False),
    sa.Column('shirt_number', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=24), nullable=True),
    sa.Column('formation_role', sa.String(length=32), nullable=True),
    sa.Column('is_starter', sa.Boolean(), nullable=True),
    sa.Column('is_substitute', sa.Boolean(), nullable=True),
    sa.Column('is_captain', sa.Boolean(), nullable=False),
    sa.Column('source_bbox_json', sa.JSON(), nullable=True),
    sa.Column('source_element_ids_json', sa.JSON(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['match_report_pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['match_report_extraction_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['squad_player_id'], ['squad_players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'team_source_name', 'shirt_number', 'source_name')
    )
    op.create_index('ix_match_report_participants_run_team', 'match_report_participants', ['run_id', 'team_id'], unique=False)
    op.create_table('match_report_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_number', sa.Integer(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('added_time', sa.Integer(), nullable=True),
    sa.Column('match_second', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('outcome', sa.String(length=40), nullable=True),
    sa.Column('body_part', sa.String(length=40), nullable=True),
    sa.Column('raw_start_x', sa.Float(), nullable=True),
    sa.Column('raw_start_y', sa.Float(), nullable=True),
    sa.Column('raw_end_x', sa.Float(), nullable=True),
    sa.Column('raw_end_y', sa.Float(), nullable=True),
    sa.Column('norm_start_x', sa.Float(), nullable=True),
    sa.Column('norm_start_y', sa.Float(), nullable=True),
    sa.Column('norm_end_x', sa.Float(), nullable=True),
    sa.Column('norm_end_y', sa.Float(), nullable=True),
    sa.Column('pitch_start_x_m', sa.Float(), nullable=True),
    sa.Column('pitch_start_y_m', sa.Float(), nullable=True),
    sa.Column('pitch_end_x_m', sa.Float(), nullable=True),
    sa.Column('pitch_end_y_m', sa.Float(), nullable=True),
    sa.Column('coordinate_space', sa.String(length=24), nullable=True),
    sa.Column('attacking_direction', sa.String(length=16), nullable=True),
    sa.Column('length_m', sa.Float(), nullable=True),
    sa.Column('angle_degrees', sa.Float(), nullable=True),
    sa.Column('attributes_json', sa.JSON(), nullable=False),
    sa.Column('source_bbox_json', sa.JSON(), nullable=True),
    sa.Column('source_element_ids_json', sa.JSON(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['match_report_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['match_report_participants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['match_report_extraction_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_match_report_events_participant', 'match_report_events', ['participant_id'], unique=False)
    op.create_index('ix_match_report_events_run_type', 'match_report_events', ['run_id', 'event_type'], unique=False)
    op.create_table('match_report_network_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('source_participant_id', sa.Integer(), nullable=True),
    sa.Column('target_participant_id', sa.Integer(), nullable=True),
    sa.Column('source_player_name', sa.String(length=160), nullable=False),
    sa.Column('target_player_name', sa.String(length=160), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('pass_share', sa.Float(), nullable=True),
    sa.Column('attributes_json', sa.JSON(), nullable=False),
    sa.Column('source_bbox_json', sa.JSON(), nullable=True),
    sa.Column('source_element_ids_json', sa.JSON(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['match_report_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['match_report_extraction_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_participant_id'], ['match_report_participants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_participant_id'], ['match_report_participants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'page_id', 'source_participant_id', 'target_participant_id')
    )
    op.create_index('ix_match_report_network_run_team', 'match_report_network_edges', ['run_id', 'team_id'], unique=False)
    op.create_table('match_report_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=24), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('metric_key', sa.String(length=120), nullable=False),
    sa.Column('value_numeric', sa.Float(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('phase', sa.String(length=40), nullable=True),
    sa.Column('dimensions_json', sa.JSON(), nullable=False),
    sa.Column('is_explicit_zero', sa.Boolean(), nullable=False),
    sa.Column('is_blank', sa.Boolean(), nullable=False),
    sa.Column('source_bbox_json', sa.JSON(), nullable=True),
    sa.Column('source_element_ids_json', sa.JSON(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['match_report_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['match_report_participants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['match_report_extraction_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_match_report_observations_participant', 'match_report_observations', ['participant_id'], unique=False)
    op.create_index('ix_match_report_observations_run_metric', 'match_report_observations', ['run_id', 'metric_key'], unique=False)
    op.create_table('match_report_spatial_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('feature_type', sa.String(length=64), nullable=False),
    sa.Column('geometry_type', sa.String(length=24), nullable=False),
    sa.Column('coordinate_space', sa.String(length=24), nullable=False),
    sa.Column('raw_geometry_json', sa.JSON(), nullable=False),
    sa.Column('normalized_geometry_json', sa.JSON(), nullable=True),
    sa.Column('canonical_geometry_json', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('phase', sa.String(length=40), nullable=True),
    sa.Column('value_numeric', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('attributes_json', sa.JSON(), nullable=False),
    sa.Column('source_element_ids_json', sa.JSON(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['match_report_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['match_report_participants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['match_report_extraction_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_match_report_spatial_run_type', 'match_report_spatial_features', ['run_id', 'feature_type'], unique=False)
    op.create_table('match_report_timeseries_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('team_source_name', sa.String(length=100), nullable=False),
    sa.Column('series_key', sa.String(length=120), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('match_second', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('raw_x', sa.Float(), nullable=True),
    sa.Column('raw_y', sa.Float(), nullable=True),
    sa.Column('attributes_json', sa.JSON(), nullable=False),
    sa.Column('source_element_ids_json', sa.JSON(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['match_report_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['match_report_participants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['match_report_extraction_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'page_id', 'series_key', 'team_source_name', 'match_second')
    )
    op.create_index('ix_match_report_timeseries_run_series', 'match_report_timeseries_points', ['run_id', 'series_key', 'match_second'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_match_report_timeseries_run_series', table_name='match_report_timeseries_points')
    op.drop_table('match_report_timeseries_points')
    op.drop_index('ix_match_report_spatial_run_type', table_name='match_report_spatial_features')
    op.drop_table('match_report_spatial_features')
    op.drop_index('ix_match_report_observations_run_metric', table_name='match_report_observations')
    op.drop_index('ix_match_report_observations_participant', table_name='match_report_observations')
    op.drop_table('match_report_observations')
    op.drop_index('ix_match_report_network_run_team', table_name='match_report_network_edges')
    op.drop_table('match_report_network_edges')
    op.drop_index('ix_match_report_events_run_type', table_name='match_report_events')
    op.drop_index('ix_match_report_events_participant', table_name='match_report_events')
    op.drop_table('match_report_events')
    op.drop_index('ix_match_report_participants_run_team', table_name='match_report_participants')
    op.drop_table('match_report_participants')
    op.drop_index('ix_match_report_payloads_page', table_name='match_report_page_payloads')
    op.drop_table('match_report_page_payloads')
    op.drop_index('ix_match_report_issues_unresolved', table_name='match_report_issues')
    op.drop_index('ix_match_report_issues_run_severity', table_name='match_report_issues')
    op.drop_table('match_report_issues')
    op.drop_index('ix_match_report_pages_run_type', table_name='match_report_pages')
    op.drop_table('match_report_pages')
    op.drop_index('ux_match_report_runs_active', table_name='match_report_extraction_runs', sqlite_where=sa.text('is_active = 1'))
    op.drop_index('ix_match_report_runs_document_created', table_name='match_report_extraction_runs')
    op.drop_index(op.f('ix_match_report_extraction_runs_status'), table_name='match_report_extraction_runs')
    op.drop_table('match_report_extraction_runs')
    op.drop_index('ix_match_report_documents_status', table_name='match_report_documents')
    op.drop_index('ix_match_report_documents_match', table_name='match_report_documents')
    op.drop_table('match_report_documents')
    op.drop_index('ix_player_injuries_player', table_name='player_injuries')
    op.drop_table('player_injuries')
    op.drop_index('ix_squad_players_team', table_name='squad_players')
    op.drop_table('squad_players')
    op.drop_table('match_report_metric_definitions')
    # ### end Alembic commands ###
