"""initial schema

Revision ID: aba802112a71
Revises: 
Create Date: 2026-06-20 14:44:41.127581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aba802112a71'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bracket_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruleset_version', sa.String(length=64), nullable=False),
    sa.Column('official_match_number', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('side_a_source_type', sa.String(length=24), nullable=False),
    sa.Column('side_a_source_ref', sa.String(length=32), nullable=False),
    sa.Column('side_b_source_type', sa.String(length=24), nullable=False),
    sa.Column('side_b_source_ref', sa.String(length=32), nullable=False),
    sa.Column('next_match_number', sa.Integer(), nullable=True),
    sa.Column('next_side', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruleset_version', 'official_match_number')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('staged_path', sa.String(length=255), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('source_cutoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_dataset_completed', 'ingestion_runs', ['dataset_type', 'completed_at'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_status'), 'ingestion_runs', ['status'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fifa_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=40), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('confederation', sa.String(length=12), nullable=False),
    sa.Column('flag_asset_uri', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_fifa_code'), 'teams', ['fifa_code'], unique=True)
    op.create_table('third_place_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruleset_version', sa.String(length=64), nullable=False),
    sa.Column('qualified_group_set', sa.String(length=12), nullable=False),
    sa.Column('target_match_number', sa.Integer(), nullable=False),
    sa.Column('third_place_group_code', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruleset_version', 'qualified_group_set', 'target_match_number')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('ruleset_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_tournaments_year'), 'tournaments', ['year'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=1), nullable=False),
    sa.Column('display_name', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'code'),
    sa.UniqueConstraint('tournament_id', 'sort_order')
    )
    op.create_index('ix_groups_tournament_sort', 'groups', ['tournament_id', 'sort_order'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('progress_iterations', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('input_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('ruleset_version', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=40), nullable=False),
    sa.Column('code_version', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint('iterations IN (10000, 100000, 1000000)'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_simulations_input_hash', 'simulations', ['input_hash'], unique=False)
    op.create_index(op.f('ix_simulations_status'), 'simulations', ['status'], unique=False)
    op.create_index('ix_simulations_tournament_created', 'simulations', ['tournament_id', 'created_at'], unique=False)
    op.create_table('team_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('rating_type', sa.String(length=24), nullable=False),
    sa.Column('rating_value', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('attack_rating', sa.Float(), nullable=True),
    sa.Column('defense_rating', sa.Float(), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'rating_type', 'source', 'effective_at')
    )
    op.create_index('ix_ratings_team_type_effective', 'team_ratings', ['team_id', 'rating_type', 'effective_at'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('official_match_number', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('team_a_id', sa.Integer(), nullable=True),
    sa.Column('team_b_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue', sa.String(length=120), nullable=False),
    sa.Column('host_country', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('team_a_id IS NULL OR team_b_id IS NULL OR team_a_id != team_b_id'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'official_match_number')
    )
    op.create_index(op.f('ix_matches_group_id'), 'matches', ['group_id'], unique=False)
    op.create_index('ix_matches_status_scheduled', 'matches', ['status', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_matches_team_a_id'), 'matches', ['team_a_id'], unique=False)
    op.create_index(op.f('ix_matches_team_b_id'), 'matches', ['team_b_id'], unique=False)
    op.create_index('ix_matches_tournament_stage', 'matches', ['tournament_id', 'stage'], unique=False)
    op.create_table('simulation_bracket_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('official_match_number', sa.Integer(), nullable=False),
    sa.Column('team_a_id', sa.Integer(), nullable=False),
    sa.Column('team_b_id', sa.Integer(), nullable=False),
    sa.Column('meeting_count', sa.Integer(), nullable=False),
    sa.Column('team_a_advance_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id', 'official_match_number', 'team_a_id', 'team_b_id')
    )
    op.create_index('ix_sim_bracket_match', 'simulation_bracket_results', ['simulation_id', 'official_match_number', 'meeting_count'], unique=False)
    op.create_index(op.f('ix_simulation_bracket_results_team_a_id'), 'simulation_bracket_results', ['team_a_id'], unique=False)
    op.create_index(op.f('ix_simulation_bracket_results_team_b_id'), 'simulation_bracket_results', ['team_b_id'], unique=False)
    op.create_table('simulation_group_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('rank_1_team_id', sa.Integer(), nullable=False),
    sa.Column('rank_2_team_id', sa.Integer(), nullable=False),
    sa.Column('rank_3_team_id', sa.Integer(), nullable=False),
    sa.Column('rank_4_team_id', sa.Integer(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['rank_1_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['rank_2_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['rank_3_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['rank_4_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id', 'group_id', 'rank_1_team_id', 'rank_2_team_id', 'rank_3_team_id', 'rank_4_team_id')
    )
    op.create_index('ix_sim_group_occurrence', 'simulation_group_results', ['simulation_id', 'group_id', 'occurrence_count'], unique=False)
    op.create_table('simulation_team_results',
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('finish_1_count', sa.Integer(), nullable=False),
    sa.Column('finish_2_count', sa.Integer(), nullable=False),
    sa.Column('finish_3_count', sa.Integer(), nullable=False),
    sa.Column('finish_4_count', sa.Integer(), nullable=False),
    sa.Column('advance_as_third_count', sa.Integer(), nullable=False),
    sa.Column('round_of_32_count', sa.Integer(), nullable=False),
    sa.Column('round_of_16_count', sa.Integer(), nullable=False),
    sa.Column('quarterfinal_count', sa.Integer(), nullable=False),
    sa.Column('semifinal_count', sa.Integer(), nullable=False),
    sa.Column('final_count', sa.Integer(), nullable=False),
    sa.Column('champion_count', sa.Integer(), nullable=False),
    sa.Column('sum_group_points', sa.Float(), nullable=False),
    sa.Column('sum_group_goals_for', sa.Float(), nullable=False),
    sa.Column('sum_group_goals_against', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('simulation_id', 'team_id')
    )
    op.create_index(op.f('ix_simulation_team_results_team_id'), 'simulation_team_results', ['team_id'], unique=False)
    op.create_table('tournament_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('draw_position', sa.Integer(), nullable=False),
    sa.Column('is_host', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'draw_position'),
    sa.UniqueConstraint('tournament_id', 'team_id')
    )
    op.create_index('ix_tournament_teams_group', 'tournament_teams', ['group_id'], unique=False)
    op.create_index(op.f('ix_tournament_teams_team_id'), 'tournament_teams', ['team_id'], unique=False)
    op.create_table('bookmaker_odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker', sa.String(length=60), nullable=False),
    sa.Column('market_type', sa.String(length=32), nullable=False),
    sa.Column('selection', sa.String(length=32), nullable=False),
    sa.Column('line_value', sa.Float(), nullable=False),
    sa.Column('decimal_odds', sa.Float(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.CheckConstraint('decimal_odds > 1'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'bookmaker', 'market_type', 'selection', 'line_value', 'snapshot_at')
    )
    op.create_index('ix_odds_match_market_snapshot', 'bookmaker_odds', ['match_id', 'market_type', 'snapshot_at'], unique=False)
    op.create_table('match_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('lambda_a', sa.Float(), nullable=False),
    sa.Column('lambda_b', sa.Float(), nullable=False),
    sa.Column('market_a', sa.Float(), nullable=True),
    sa.Column('market_draw', sa.Float(), nullable=True),
    sa.Column('market_b', sa.Float(), nullable=True),
    sa.Column('model_a', sa.Float(), nullable=False),
    sa.Column('model_draw', sa.Float(), nullable=False),
    sa.Column('model_b', sa.Float(), nullable=False),
    sa.Column('final_a', sa.Float(), nullable=False),
    sa.Column('final_draw', sa.Float(), nullable=False),
    sa.Column('final_b', sa.Float(), nullable=False),
    sa.Column('components_json', sa.JSON(), nullable=False),
    sa.Column('data_quality', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'model_version', 'input_hash')
    )
    op.create_index('ix_predictions_match_generated', 'match_predictions', ['match_id', 'generated_at'], unique=False)
    op.create_table('match_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('team_a_goals_90', sa.Integer(), nullable=False),
    sa.Column('team_b_goals_90', sa.Integer(), nullable=False),
    sa.Column('team_a_extra_time_goals', sa.Integer(), nullable=True),
    sa.Column('team_b_extra_time_goals', sa.Integer(), nullable=True),
    sa.Column('team_a_penalties', sa.Integer(), nullable=True),
    sa.Column('team_b_penalties', sa.Integer(), nullable=True),
    sa.Column('winner_team_id', sa.Integer(), nullable=True),
    sa.Column('team_a_yellows', sa.Integer(), nullable=True),
    sa.Column('team_b_yellows', sa.Integer(), nullable=True),
    sa.Column('team_a_indirect_reds', sa.Integer(), nullable=True),
    sa.Column('team_b_indirect_reds', sa.Integer(), nullable=True),
    sa.Column('team_a_direct_reds', sa.Integer(), nullable=True),
    sa.Column('team_b_direct_reds', sa.Integer(), nullable=True),
    sa.Column('team_a_yellow_direct_reds', sa.Integer(), nullable=True),
    sa.Column('team_b_yellow_direct_reds', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('team_a_goals_90 >= 0 AND team_b_goals_90 >= 0'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'revision')
    )
    op.create_index('ix_match_results_match_current', 'match_results', ['match_id', 'is_current'], unique=False)
    op.create_index('ux_match_results_current', 'match_results', ['match_id'], unique=True, sqlite_where=sa.text('is_current = 1'))
    op.create_table('prediction_market_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_market_id', sa.String(length=120), nullable=False),
    sa.Column('contract_id', sa.String(length=120), nullable=False),
    sa.Column('market_type', sa.String(length=32), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('selection', sa.String(length=60), nullable=False),
    sa.Column('yes_price', sa.Float(), nullable=False),
    sa.Column('no_price', sa.Float(), nullable=True),
    sa.Column('best_bid', sa.Float(), nullable=True),
    sa.Column('best_ask', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('liquidity', sa.Float(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('yes_price >= 0 AND yes_price <= 1'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'contract_id', 'selection', 'snapshot_at')
    )
    op.create_index('ix_market_prices_match_snapshot', 'prediction_market_prices', ['match_id', 'snapshot_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_prices_match_snapshot', table_name='prediction_market_prices')
    op.drop_table('prediction_market_prices')
    op.drop_index('ux_match_results_current', table_name='match_results', sqlite_where=sa.text('is_current = 1'))
    op.drop_index('ix_match_results_match_current', table_name='match_results')
    op.drop_table('match_results')
    op.drop_index('ix_predictions_match_generated', table_name='match_predictions')
    op.drop_table('match_predictions')
    op.drop_index('ix_odds_match_market_snapshot', table_name='bookmaker_odds')
    op.drop_table('bookmaker_odds')
    op.drop_index(op.f('ix_tournament_teams_team_id'), table_name='tournament_teams')
    op.drop_index('ix_tournament_teams_group', table_name='tournament_teams')
    op.drop_table('tournament_teams')
    op.drop_index(op.f('ix_simulation_team_results_team_id'), table_name='simulation_team_results')
    op.drop_table('simulation_team_results')
    op.drop_index('ix_sim_group_occurrence', table_name='simulation_group_results')
    op.drop_table('simulation_group_results')
    op.drop_index(op.f('ix_simulation_bracket_results_team_b_id'), table_name='simulation_bracket_results')
    op.drop_index(op.f('ix_simulation_bracket_results_team_a_id'), table_name='simulation_bracket_results')
    op.drop_index('ix_sim_bracket_match', table_name='simulation_bracket_results')
    op.drop_table('simulation_bracket_results')
    op.drop_index('ix_matches_tournament_stage', table_name='matches')
    op.drop_index(op.f('ix_matches_team_b_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_team_a_id'), table_name='matches')
    op.drop_index('ix_matches_status_scheduled', table_name='matches')
    op.drop_index(op.f('ix_matches_group_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index('ix_ratings_team_type_effective', table_name='team_ratings')
    op.drop_table('team_ratings')
    op.drop_index('ix_simulations_tournament_created', table_name='simulations')
    op.drop_index(op.f('ix_simulations_status'), table_name='simulations')
    op.drop_index('ix_simulations_input_hash', table_name='simulations')
    op.drop_table('simulations')
    op.drop_index('ix_groups_tournament_sort', table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_tournaments_year'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_table('third_place_assignments')
    op.drop_index(op.f('ix_teams_fifa_code'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_ingestion_runs_status'), table_name='ingestion_runs')
    op.drop_index('ix_ingestion_dataset_completed', table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_table('bracket_slots')
    # ### end Alembic commands ###
